name: print message
description: "prints message"
inputs:
  message:
    description: "A message to be displayed"
    required: false
    default: "This is just holding place for future work flows.."

runs:
  using: "composite"
  steps:
    - name: "print message"
      id: print-id
      run: echo "${{ inputs.message }}"
      shell: bash