name: "placeholder"
on:
  push:
    branches:
      - master
#    paths-ignore:
#      - .github/**
jobs:
  store-message:
    runs-on: ubuntu-latest
    outputs:
      message: ${{ steps.print_message.outputs.message }}
    steps:
      - name: store message
        id: print_message
        run: echo 'message="This is just holding place for future work flows.. "' > $GITHUB_OUTPUT
  print-message:
    runs-on: ubuntu-latest
    needs: store-message
    steps:
      - name: print the message
        run: echo "${{ needs.store-message.outputs.message }}"